export const WS_URL = "ws://localhost:8080";
export const INIT_GAME = "init_game";
export const MOVE = "move";
export const GAME_OVER = "game_over";
export const PENDING_GAME = "pending_game";

export const boardColorsList = {
  CLASSIC_GREEN: {
    darkSquare: "bg-[#18B350] hover:brightness-110",
    lightSquare: "bg-[#DCFCE6] hover:brightness-107",
  },
  DREAM_BLUE: {
    darkSquare: "bg-[#8CA2AD] hover:brightness-110",
    lightSquare: "bg-[#DEE3E6] hover:brightness-105",
  },
  WOOD: {
    darkSquare: "bg-[#76402D]",
    lightSquare: "bg-[#C09762]",
  },
  MARBLE: {
    darkSquare: "bg-[#000000]",
    lightSquare: "bg-[#ced4da]",
  },
  BREAD_BROWN: {
    darkSquare: "bg-gradient-to-r from-slate-600 to-slate-800",
    lightSquare: "bg-gradient-to-l from-slate-200 to-slate-500",
  },
};

export const sampleGame = [
  "e4",
  "c5",
  "Nf3",
  "d6",
  "d4",
  "cxd4",
  "Nxd4",
  "Nf6",
  "Nc3",
  "a6",
  "Bc4",
  "e6",
  "Bb3",
  "b5",
  "Bg5",
  "Be7",
  "Qf3",
  "Qc7",
  "e5",
  "Bb7",
  "exd6",
  "Bxd6",
  "Qe3",
  "Bc5",
  "O-O-O",
  "Nc6",
  "Qxe6+",
  "fxe6",
  "Nxe6",
  "Qe5",
  "Nxg7+",
  "Kf8",
  "Ne6+",
  "Kf7",
  "Rhe1",
  "Qxe1",
  "Nxc5+",
  "Kg6",
  "Rxe1",
  "Kxg5",
  "Nxb7",
  "Nd4",
  "Nd6",
  "Rhf8",
  "f3",
  "b4",
  "Nce4+",
  "Nxe4",
  "Rxe4",
  "Nxb3+",
  "axb3",
  "a5",
  "Rg4+",
  "Kf6",
  "Ne4+",
  "Ke5",
  "Rh4",
  "a4",
  "bxa4",
  "Rxa4",
  "Nc5",
  "Ra1+",
  "Kd2",
  "Rg8",
  "g3",
  "Rf1",
  "Ke2",
  "Rb1",
  "Rxb4",
  "Kd5",
  "Ne4",
  "Kc6",
  "h4",
  "Rh1",
  "Rc4+",
  "Kb6",
  "b4",
  "Rd8",
  "Rc5",
  "Ra8",
  "c3",
  "Ra2+",
  "Ke3",
  "Re1+",
  "Kf4",
  "Rf1",
  "Rh5",
  "Ra8",
  "Rh6+",
  "Kb5",
  "Nd6+",
  "Ka4",
  "Rxh7",
  "Kb3",
  "Rc7",
  "Rd8",
  "Nf5",
];

export const games = [
  {
    name: "Blitz",
    types: [
      { baseTime: 3, increment: 0 },
      { baseTime: 3, increment: 2 },
      { baseTime: 5, increment: 0 },
    ],
  },
  {
    name: "Bullet",
    types: [
      { baseTime: 1, increment: 0 },
      { baseTime: 1, increment: 1 },
      { baseTime: 2, increment: 1 },
    ],
  },
  {
    name: "Rapid",
    types: [
      { baseTime: 10, increment: 0 },
      { baseTime: 15, increment: 10 },
    ],
  },
];
